name: pr-closed
description: Close pr-closed issues with no activity
resource: repository

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Step 1 - Add inactive-2-weeks label to pull requests labeled do not merge with no activity for 14 days
      frequencies:
      - daily:
          time: 11:0
      filters:
      - isOpen
      - isPullRequest
      - isNotLabeledWith:
          label: inactive-2-weeks
      - isNotLabeledWith:
          label: inactive-4-weeks
