name: odsp-cleanup
description: Close issues labeled automation:Closed
resource: repository

configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - isIssue
          - hasLabel:
              label: automation:Closed
        actions:
          - closeIssue
          - lockIssue
