name: API Doctor validation

on:
   workflow_dispatch
#  pull_request:
#    branches:
#    - main
#    - live
#    paths:
#    - api-reference/**

permissions:
  contents: read

env:
  APIDOCTOR_VERSION: 1.2.2312.152

jobs:
  validate-docs:
    name: Validate reference docs
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Install NuGet
      uses: NuGet/setup-nuget@v2.0.0
    - name: Install ApiDoctor from NuGet
      run: nuget install ApiDoctor -Version $APIDOCTOR_VERSION -OutputDirectory ./nuget -NonInteractive --DisableParallelProcessing
    - name: Run ApiDoctor
      run: ./tools/apidoc help
    - name: Checkout docs repo
      uses: actions/checkout@v4.1.3
