name: Update cloud support status

on:
  schedule:
  - cron: 0 11 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cloud-support:
    name: Update cloud support
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.3
      name: Checkout docs repo
    - uses: actions/checkout@v4.1.3
      name: Checkout metadata repo
      with:
        repository: microsoftgraph/msgraph-metadata
    - run: ls
