name: Update cloud support status

on:
  schedule:
  - cron: 0 11 * * 1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cloud-support:
    name: Update cloud support
    runs-on: ubuntu-latest
    steps:
    - name: Checkout docs repo
      uses: actions/checkout@v4.1.3
      with:
        path: docs
    - name: Checkout metadata repo
      uses: actions/checkout@v4.1.3
      with:
        repository: microsoftgraph/msgraph-metadata
        path: metadata
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Install hidi
      run: dotnet tool install microsoft.openapi.hidi -g
    - name: Apply XSLT to CSDL files
      working-directory: ./metadata
      shell: pwsh
      run: |
        ./transforms/csdl/transform.ps1 -xslPath preprocess_csdl.xsl -inputPath ../../schemas/v1.0-Prod.csdl -outputPath ../../transformed_v1.0-Prod.csdl -addInnerErrorDescription $true -removeCapabilityAnnotations $false -csdlVersion v1.0
    - name: Transform CSDL with hidi
      run: hidi transform --cs transformed_v1.0-Prod.csdl -o ./schemas/openapi/v1.0/Prod.yml --co -f Yaml --sp ./conversion-settings/openapi.json
      working-directory: ./metadata
    - run: ls
      working-directory: ./metadata
