name: Request TOC generation

on:
  issue_comment:
    types:
    - created

jobs:
  request_toc_gen:
    name: Request TOC generation
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#gen-toc') && github.event.issue.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo TOC generation requested for base $BASE_REF, head $HEAD_REF
      env:
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.head_ref }}
